### ISSUE TITLE
FR: Palette loading and saving

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#17]
It would be great if we could load our own color palettes.

Here is one I'm particularly interested in having as a swatch palette menu:
https://lospec.com/palette-list/ansi32

![image](https://github.com/mkrueger/icy_draw/assets/412263/d7e579e2-1aa2-46c9-93e5-57b3ad6e6e4a)

.pal format that gimp uses would be fine I think.

**Comment by mkrueger** [comment]
implemented.
