### ISSUE TITLE
Layer controls missing on File -> New -> Ansimation

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#22]
Layer UI controls are missing when using File -> New -> Ansimation.

![image](https://github.com/mkrueger/icy_draw/assets/412263/a9f2ba28-24c2-41f3-89f4-8f63895e6f39)

Also missing preview, char table and channels:
![image](https://github.com/mkrueger/icy_draw/assets/412263/fee91ead-5544-40a7-a98b-18d210aca60b)

**Comment by grymmjack** [comment]
![image](https://github.com/mkrueger/icy_draw/assets/412263/234dde0e-1096-4182-b9c1-c5a04e5959bf)

**Comment by grymmjack** [comment]
Closing the Ansimation document brings back the controls properly with the other file remaining open, etc.

**Comment by mkrueger** [comment]
Setting to tabs should work.

**Comment by mkrueger** [comment]
Should be fixed.
