### ISSUE TITLE
FR: Copy palette between documents

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#26]
Since we can have multiple documents open, and even side by side (awesome), when you do the stuff for palette loading/saving, it would be sick if there was a COPY option from one documents palette, then PASTE in the other document.

Think of this workflow:

You find a piece of art using a custom palette that you find the artwork and artist very inspiring.

You would like to reproduce that.

There is no palette file so you could save the palette from the inspiring artwork, then load it back in on the other document, but it would be better if you could just copy/paste between them.

**Comment by mkrueger** [comment]
Can do but I think Palettes work differently than you think or moebius does.

**Comment by mkrueger** [comment]
A very unlikely use case - added an export to palette library. 

It's possible to copy the exported file to palette directory.
