### ISSUE TITLE
Toggle reference image when never set shows strange display

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#28]
Toggling a reference image before one is set shows something like this:
![image](https://github.com/mkrueger/icy_draw/assets/412263/a6d2239e-bdcc-452d-a0bd-351aa42277e9)

Not shown in the screenshot: Under those triangles at the bottom, it's randomly showing bits and pieces of a single row of text.

**Comment by mkrueger** [comment]
Good finding and a very strange effect.
