### ISSUE TITLE
Clicking in character table bypasses undo

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#3]
Create a new doc.
Make the character table visible.
Click a character in the character table.
Inserted character in the doc. Great.
But now, try to undo with `CTRL-Z`
Not possible.

CTRL-Z in menu also is grayed out.

So clicking is bypassing undo.

**Comment by mkrueger** [comment]
Maybe the right side is better for the char table.  I experimented a bit around with it. 

Anyways it's now reworked - was just a placeholder before.
