### ISSUE TITLE
Half-block isn't drawing with transparency

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#31]
Disabling BG when drawing with half-block mode on I would expect transparency to be the background color.

It isn't, it's black, and in my tests it's always black, even if I changed the background color and enabled BG when drawing, still black.

See two shots:

This shows the issue with black not transparent
![image](https://github.com/mkrueger/icy_draw/assets/412263/fcf1cf87-005b-4e29-931b-c6eecea4a509)

This shows issue with not using background color at all:
![image](https://github.com/mkrueger/icy_draw/assets/412263/67e816a1-4065-44fe-a8b0-b37e9c9fe3c3)

In this shot:
1. Draw with halfblock mode.
2. Enable BG.
3. Choose non black color
4. Result

**Comment by mkrueger** [comment]
ATM there isn't a transparent color - half blocks chose the correct color on draw currently.

However it's possible to introduce a transparent color for fg/bg - but it's something for a future extension.

**Comment by grymmjack** [comment]
Ok. Got it on transparent support. 

Still it is not honouring the non black background. Look at the shot.

**Comment by mkrueger** [comment]
No only when you redraw on that layer. There is no transparent color atm.

Half blocks pick up the colors from the current layer for that reason - which is black in that case.

**Comment by mkrueger** [comment]
Added half block transparency. Would be nice if you could test it a bit. 

Wanted to postpone that feature.

**Comment by grymmjack** [comment]
This works tremendously well!

I love how you made it so that when the layers are singular and on full alpha it acts as a "transparency" which is really just determining how the blocks should be laid out minus any background color at all.

Then when we enable layers beneath any half block drawn ones on top of something with art under, it automatically inherits the background for the non-filled  in part of the half blocks! GENIUS!

What this means is at any time our art is always 100% 1:1 with how it will look on export. This is an incredibly clever way to do it, and when I reported the issue I didn't realize it was that deep.

<3 Thanks!
