### ISSUE TITLE
FR Real-time update while drawing, or pause to update composite render

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#32]
When drawing, currently the display isn't updated until we let go of the button.

![image](https://github.com/mkrueger/icy_draw/assets/412263/c11b9d25-3037-4088-b83b-c6ec56086ac5)
In this example, I am drawing a black box, under a font layer.

However, the display isn't updated as I drag  the box, it's instead obstructing the view of the font, which makes it difficult to align the box under the font.

Until I let go of the button, at which time it renders:
![image](https://github.com/mkrueger/icy_draw/assets/412263/d9ea492d-e3eb-49f2-a45d-6f16b4bfd6a0)

But this workflow is kind of poor. It would be nice if either:

1. A real-time update could happen as we work. or...
2. A pause while dragging for a second or two will update the display to give us a preview of what we're doing.

This is problematic because what we have to do now instead is use trial and error to line things up.
1. Try to figure out where to draw the box start, and hope it's correct.
2. Try to drag until we think it looks like it will cover what we want and end where we want.
3. When it's wrong, now undo, and repeat 1-3 until correct.

**Comment by mkrueger** [comment]
fixed.
