### ISSUE TITLE
FR Nudge with cursors like gimp/photoshop while floating selection active

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#37]
Since we're so close to being 1:1 with GimpShop :) it would be nice if:

Floating selections could be nudged like GimpShop.

- Arrows move by 1 column/character
- SHIFT+Arrows move by 10x column/character (or maybe 5? since our resolution is so small - maybe as a config option?)

I know this is being really needy because the resolution is so low already it's VERY precise to nudge, so not as huge a deal as it is when you are requiring precision in higher resolution canvases like in GimpShop photo editing or UI design.

**Comment by mkrueger** [comment]
Implemented - however I've slight problems selecting the editor programatically. Some things are still buggy in egui - focusing is certainly on the more instabile side atm :/.
