### ISSUE TITLE
`CTRL-A` to select all only works in Arrow tool mode

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#4]
Currently when another tool is selected like paintbrush, `CTRL-A` to select all is not working.

It looks like only the arrow tool supports `CTRL-A` select all.

It would be great to have `CTRL-A` and block operations for ALL modes of editing.

**Comment by mkrueger** [comment]
Block operations should work for all modes of editing - there is no restriction on them. If there is no selection they work on the whole layer by default.

For example try cut & paste and ctrl+alt + arrows - that are the scroll operations - they work on the floating layer

**Comment by mkrueger** [comment]
closing. Added selection mode. Select All doesn't make sense much for other modes.
