### ISSUE TITLE
icy_draw doesn't open for me on Windows 10

### ISSUE THREAD

**Issue by nolageek** [mkrueger/icy_draw#40]
The last few times I've downloaded icy_draw, it doesn't open for me on Windows 10 (64 bit). I've tried the exe and the msi installer and I click on the icon and nothing happens. The same thing is happening for me with icy_term. If I look in the install directories or in the user AppData directories, they only contain the exe file or are empty (respectively.)  No log file.  Nothing in Windows Event Viewer either.

**Comment by mkrueger** [comment]
Y have a bug report like that for icy_term as well: 
https://github.com/mkrueger/icy_term/issues/44

Not sure what to do there since i can't repro that. I assume it has to do with the opengl backend that it doesn't work on some machines. Without someone who compiles icy_term/icy_draw or icy_view on one of those machines and gives me the console output I suppose I'm stuck on that.

Which graphics card do you have?

**Comment by nolageek** [comment]
The laptop I tried it on has a Intel(R) Iris(R) Xe Graphics
My BBS server has a AST1400/2400, ASPEED compatible

**Comment by mkrueger** [comment]
Can you try:
https://github.com/mkrueger/icy_draw/releases/download/0.1.0/icy_draw_0.1.0_windows_exe_opengl_fix.zip

I changed the opengl version to something newer - should be supported by this graphics chip. But I don't know if this works. Without an debug build & console output.

**Comment by mkrueger** [comment]
Or maybe a DLL is missing: 

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by mkrueger** [comment]
```
C:\Users\bbs\Downloads\icy_draw-debug-build-win32>icy_draw.exe
2023-10-15T14:32:36.873636200-04:00 INFO icy_draw - Starting iCY DRAW 0.1.0
2023-10-15T14:32:36.988341900-04:00 ERROR eframe::native::run::glow_integration - failed to set swap interval due to error: Error { raw_code: None, raw_os_message: None, kind: NotSupported("swap contol extrensions are not supported") }
thread 'main' panicked at 'An OpenGL error occurred: egui_glow requires opengl 2.0+.
```

Try to upgrade the graphics card drivers. The tech stack icy draw uses requires opengl - that's why the UI is so fluid.

**Comment by nolageek** [comment]
The onboard video chipset in the server only supports OpenGL up to 1.4 - any chance you could support older version?
