### ISSUE TITLE
FR Text Input improvements

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#41]
Right now the text input tool is proving a bit difficult to use. This is the traditional way in which we draw so it's kind of a big deal.

When drawing with Text Input using F1-F9 and then interacting with the UI:

1. It isn't clear where the cursor is in the drawing any more because the cursor disappears.
2. After for example, choosing a color in the palette, the cursor is still missing in the doc.
3. The drawing canvas will only display a cursor again after clicking on the canvas to restore input focus to it.
4. This means if we need to interact with anything else in the UI while we are drawing traditionally (text mode) the cursor position has to be guessed at to be restored.

I suggest one or more of the following to make this a better experience:

- Make some kind of "cursor placeholder marker" when we are in text input UI and have to click another part of the interface which would make it easy to remember where we are. How this would work is if you are drawing with text input, and click away, a box or some kind of outline or something indicates where the cursor was at when you clicked away from the canvas. This would allow us to simply click that spot again to restore it.

- When drawing with the Text Input tool, let clicking on the canvas after we have lost input focus on the UI return to the cursor position was no matter where we click on the canvas. 

- Better would be automatically restoring input focus after a click on the UI widgets for us. That is, the artist is drawing with text input mode tool, then they click on the color palette or a layer, but immediately afterwards on mouse-up the cursor is restored in text input tool. 

Workaround I found: clicking on the empty area of the canvas pane outside of the drawing area will keep the cursor position, and restore it, it's just a weird way to have to work given the way it works in other programs, etc.

Here is the workaround:
![icydraw-color-cursor-workaround](https://github.com/mkrueger/icy_draw/assets/412263/1f8cf435-1b32-46d8-8f38-a9e8b47fca90)

Thanks

**Comment by grymmjack** [comment]
I compared the behavior in icy draw with moebius, and yeah, it's different in that there is a saved cursor position in moebius that automatically gets restored when the user switches back to the text input tool.

Also a helpful feature in moebius that could possibly be used here is a flashing box cursor - this lets us see the cursor easier.

![image](https://github.com/mkrueger/icy_draw/assets/412263/e08e4510-2c6e-47a3-ad3f-2254d61a492f)

https://github.com/mkrueger/icy_draw/assets/412263/dd8f0c7b-e202-4bf8-8e2b-440223d8da32

**Comment by mkrueger** [comment]
the cursor disappear thing is a bug in egui - haven't found any work around yet.

**Comment by mkrueger** [comment]
Maybe I've a work around but it's really hacky.
