### ISSUE TITLE
Cursor offset / grid oddity when preview window navigator is offset or zoom is not a multiple of 100%

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#43]
The cursor is offset when the preview navigator box is offset

![image](https://github.com/mkrueger/icy_draw/assets/412263/67f1ebcf-2656-4801-9500-9cbd1e4e051a)

Here you can see when the preview navigator is flush left, it looks correct
![image](https://github.com/mkrueger/icy_draw/assets/412263/448dae1c-433d-4b15-bd55-13f3addba7cd)

Maybe what you could do is snap the cursor to the grid of the characters? 

I love how the preview window navigator box can just smoothly select a part to work on, but have the cursor be offset like this is a jarring thing. 

If it's easier you could snap the preview window navigator box to a ratio for the cursor to stay? Dunno.

Thanks!

**Comment by grymmjack** [comment]
It's even easier to see this when the grid is enabled:
![image](https://github.com/mkrueger/icy_draw/assets/412263/55ee6acf-293d-41f3-81be-1392bc561a41)

**Comment by grymmjack** [comment]
It appears that zoom that isn't also a factor of 100% also draws oddly and the grid renders oddly. The cursor is offset as well.

Here I am zoomed to 170% and you can see:
![image](https://github.com/mkrueger/icy_draw/assets/412263/9d5cacbd-723c-4e77-a612-83b2c70ff8a2)

**Comment by mkrueger** [comment]
fixed the caret bug - should be in 0.1.2+
