### ISSUE TITLE
Can't add spaces in sauce comments.

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#46]
Here I am trying to type "space" and it like jiggles, but doesn't allow a space oddly?

![image](https://github.com/mkrueger/icy_draw/assets/412263/38c4b0ed-a31b-495a-b3f7-a674c6482340)

What I tried to type:
`This is for my little QB64 WIP game called Dungeon.`

**Comment by grymmjack** [comment]
Strangely after clicking OK to commit the spaceless sauce comment, and clicking again edit | sauce... when a sauce comment exists, I CAN add spaces within the characters which already exist (that is in their range), but not at the end. It won't let me add spaces to the end.

There must be a length of the string or something in the input routine that's screwed up?

![image](https://github.com/mkrueger/icy_draw/assets/412263/bb2ef714-9faa-483d-8963-c07b520f233b)

**Comment by mkrueger** [comment]
issue is that space is the eol filler char in sauce format. will be fixed in the next release (0.1.2+)
