### ISSUE TITLE
Lightened colors during Win11 screenshot

### ISSUE THREAD

**Issue by richinseattle** [mkrueger/icy_draw#47]
When using the screenshot function of Windows 11,the resulting colors are somehow shifted to a lighter palette. Lt.Grey appears white, etc. performing the same action in Pablo or others does not have this result. 

![image](https://github.com/mkrueger/icy_draw/assets/1887673/91d02cfd-def2-4244-8bd2-e1f1b129683f)

![image](https://github.com/mkrueger/icy_draw/assets/1887673/f008b03c-9cf1-40fb-bba1-0f94ac72a4fe)

**Comment by mkrueger** [comment]
It's interesting - but it would've been nice if you could provide secreen shots of icy_draw as well.

**Comment by mkrueger** [comment]
![grafik](https://github.com/mkrueger/icy_draw/assets/341098/a2efea6c-977e-4d26-a296-44151a8c5d4e)
![grafik](https://github.com/mkrueger/icy_draw/assets/341098/d2d7999b-8bc1-43ff-9286-ef7ea1c67a0f)

**Comment by mkrueger** [comment]
Closing that one. This purely depends on graphics card drivers.

**Comment by richinseattle** [comment]
The first screenshot was icy_draw .. I am using a 3090 on Windows 11 with latest nvidia drivers.. pretty common configuration.
