### ISSUE TITLE
FR Setting to change color hotkey behaviors from 1-8 to 0-7

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#53]
The implementation that exists (and thank you!) for setting colors using CTRL and ALT uses range 1-8 but that is not really the standard way. I discussed this with you on stream, and you said that you didn't want to put this very specific edge case option stuff in the UI, hence we discussed putting in file.

This FR is to allow a setting in the file to change the range of the color hotkeys from 1-8 to 0-7

So 0 = black, and 1 = blue
vs.
1 = black and 2 = blue.

The reason for this is because it's how it is setup since DOS days, in programming, EGA palette indexes, etc. and also how it works in other programs like pablo, moebius, etc.

**Comment by mkrueger** [comment]
Mapped zoom reset to ctrl+backspace
