### ISSUE TITLE
CTRL+C when a selection is active does not seem to allow the menu Paste As features to be used

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#56]
![image](https://github.com/mkrueger/icy_draw/assets/412263/25528f71-1c16-496f-9c0d-8831710cab56)

Here I have selected a small section of the document, then used CTRL+C to copy it.

I expected the edit paste as new brush to be available, but it was not.

This does work fine if we use the menu commands with the mouse clicks.

**Comment by grymmjack** [comment]
Note: somehow the drawing was in a weird state. I exited the program and reopened it loading the same icy file as before, and CTRL+C worked as expected and allowed me to use edit paste as.

There might be something related to the 9px font thing I don't know.

**Comment by mkrueger** [comment]
still an issue.
