### ISSUE TITLE
Half block drawing when layer is in Attribute mode has transparency bug

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#57]
Half block leaving transparent color above layer under composited.

Layer setup:
![image](https://github.com/mkrueger/icy_draw/assets/412263/8ae47a63-7871-4669-b1ce-c78a269af1a2)

Anomaly with the transparency:
![image](https://github.com/mkrueger/icy_draw/assets/412263/ba562b9a-456e-4e23-8f10-4dbc5e11f1c4)

**Comment by mkrueger** [comment]
Still happens with 1 layer.
