### ISSUE TITLE
XB Extended Font always picks character from Font Page 0 in Text input mode and in Paint Brush mode

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#58]
Reproduce:

1. Create new XB Extended Font (a)
2. Click Text input tool
3. In Text input tool, click Font Page arrow tool to the right to go to page 1
4. Choose a different font than what is on Font Page 1 from Fonts -> Select Font...
5. Click a character in the character map to insert from Font Page 1
6. Character inserts from Font Page 0 (b)
7. Do the same with Paint brush and choose Character - looks like it's ignoring character from Font Page 0 selected. (c)

(a) ![image](https://github.com/mkrueger/icy_draw/assets/412263/c4b3d09a-548a-4b57-b1ae-9083de769e53)

(b) ![image](https://github.com/mkrueger/icy_draw/assets/412263/1aca004c-bcc8-4d8b-b78f-bfbc057be5b5)

(c) ![image](https://github.com/mkrueger/icy_draw/assets/412263/445d1154-4c91-43b3-9a5e-02bfa04aa03f)

**Comment by mkrueger** [comment]
Fixed by https://github.com/mkrueger/icy_draw/commit/df0cf9891ad6aafab846a87d5e9669dfb0af440d
