### ISSUE TITLE
You should not be able to delete every layer

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#6]
Currently you can delete every layer.

You should not be able to do this. Instead, if the user is attempting to delete the only layer, the layer should be deleted, but a new one immediately created and focused for input afterwards. This way the app never becomes "impossible to draw in".

This is a common theme in most layer based programs.

Another option is if there is only 1 layer, disallow the delete option. The feature request I made to add clear layer would complement that way of doing things.

**Comment by mkrueger** [comment]
y doesn't really make sense to get into an impossible to draw state - I don't think I like the idea of preventing the delete option - creating a new empty layer is better.
