### ISSUE TITLE
Video flicker/instability - Ubuntu 23.10 with AMD Radeon HD 8570 video card

### ISSUE THREAD

**Issue by robbiew** [mkrueger/icy_draw#60]
When editing a file, the screen flickers, the mouse duplicates itself into a stream, and the main body area becomes transparent so that it shows the window beneath IcyDraw.

I _suspect_ it's a video card compatibility issue?  AMD Radeon HD 8570. Ubuntu is handling the video driver.

**Comment by robbiew** [comment]
Just to confirm, I tested with an NVIDIA GTX 1070 Mini and the problem is not present when using this video card - looks like it's an incompatibility with AMD Radeon HD 8570.

**Comment by mkrueger** [comment]
Can't do much here - it's on opengl level. Maybe moving from glut to wgpu may help there but I can't promise to do that in forseeable future. (And I doubt it'll work in that case)
