### ISSUE TITLE
Bug: "Rows"/"columns" coordinate labels when using selection tools are reversed

### ISSUE THREAD

**Issue by TheGreenHerring** [mkrueger/icy_draw#63]
When using the Text Input tool, the "Ln" (line) and "Col" (column) labels correctly refer to the line and column where the text input cursor is. However, if you make a rectangular selection using the Text Input tool or the Select tool, the "Rows"/"Columns" coordinate labels are reversed: the "columns" counter refers to how many _rows_ are selected, while the "rows" counter refers to how many _columns_ are selected. (Running version 0.2.0 in Windows 10 64-bit.)
<img width="341" alt="IcyDraw_0 2 0_LnCol" src="https://github.com/mkrueger/icy_draw/assets/79224555/2192b4c3-713f-46c5-98f9-9a354d58170b">
<img width="331" alt="IcyDraw_0 2 0_ColumnsRows" src="https://github.com/mkrueger/icy_draw/assets/79224555/1aa1f003-7011-428b-8002-012069be7ee4">

**Comment by mkrueger** [comment]
Was reversed in german translation, didn't notice :/
