### ISSUE TITLE
New layers should be transparent by default

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#7]
When creating a new layer currently it is created with all black opaque background in every character cell.

It would be better to create a new layer completely transparent. This is the default way of working in the majority of layer based programs.

**Comment by grymmjack** [comment]
It is possible the default layer is opaque. I'm trying to reproduce this one.

**Comment by grymmjack** [comment]
Yes, the default "Background" layer is opaque, and then when one deletes it and removes all other layers, when it is recreated it is again recreated opaque. So new layers by default are transparent unless the new layer is being made when no others already exist.

**Comment by mkrueger** [comment]
Fixed https://github.com/mkrueger/icy_engine/commit/9b4da0933a2bceb2baf52e6b7984db819c101524
