### ISSUE TITLE
Program writes SAUCE file size reports that are one byte more than the actual file size

### ISSUE THREAD

**Issue by TheGreenHerring** [mkrueger/icy_draw#71]
When writing the SAUCE file size bytes, this program currently writes the file size as one byte more than the actual number of bytes that the original file contents are. The effects of this are most apparent with .ANS files loaded by Moebius, as this causes the initial EOF character of the SAUCE block to be erroneously printed within the image (as the code page 437 glyph, the →) if there is room in the picture's width for it. Here's an example from [the just-released 2024 update of my game *Cyber Purge*](https://thegreenherring.itch.io/cyber-purge-zzt), where I used Icy Draw to compress all the ANSI and XBIN files provided with the game, showing what the picture looked like before the reported file size was manually corrected prior to release, with an arrow that's not supposed to be there:

![HARMONIOUS_2 - Wrong](https://github.com/mkrueger/icy_draw/assets/79224555/8129530f-5f60-4312-aecd-3c9bb8f212df)
Here is a ZIP file of the ANS file before and after it was corrected: [HARMONIOUS_2.ANS - Right and Wrong.zip](https://github.com/mkrueger/icy_draw/files/14622776/HARMONIOUS_2.ANS.-.Right.and.Wrong.zip)

This qualifies as a bug because [the SAUCE specs](https://www.acid.org/info/sauce/sauce.htm) specifically state that the EOF character is part of the SAUCE block and *not* the original file contents, and thus it should not be included in file size calculations:

> Applied to a file, SAUCE has 4 parts: The original file contents, an End-Of-File or EOF character (Decimal 26, Hex 1A, Ctrl+Z), an optional comment block and the SAUCE record.

**Comment by mkrueger** [comment]
Thanks.
Reworked the sauce code today - had this on the todo list I'll need to update the icy_engine code to swicth to the new sauce handling code.

**Comment by mkrueger** [comment]
took a little break from icy_board work today & updated icy_engine/view and icy_draw to the brand new sauce handling library icy_sauce :). Found some little differences between the sauce spec and my old implementation. I hope the new one fixes that.
